### ISSUE TITLE
Cosmetic: Improve versioning

### ISSUE THREAD

**Issue by samo790** [krabobmkd/amigamame#13]
Actually versioning only prints the version of the exe ---> 0.106 a0.1
However it would be nice to have a "full" versioning with more details

"Mame 0.106 a0.1"

**Comment by krabobmkd** [comment]
Granted.
Will be done on Beta4.

**Comment by samo790** [comment]
Maybe even better adding also the CPU compiled on

"Mame 0.106 a0.1 68000"

Or if generic, just 68k

**Comment by samo790** [comment]
An extra space is missed between the version number of MAME and the processor unit :-)

Is now:

0.03c68060

But should be:

0.03c 68060
