### ISSUE TITLE
Quick test of games

### ISSUE THREAD

**Issue by stephbb75** [krabobmkd/amigamame#15]
Quick test of games, but ROM for the 37b2! (didn't have time to look for another ;-) )
On all tests:
- Problem with the keys to play, often pressing 2 keys does not work, for example shoot + up then release up and press down, the down is not taken into account, you have to release all the keys to be able to continue

1941: works
1943: Missing sprites (planes)
Bad dude: extremely slow
double dragon: works but slow
RTYPE: works
Drift Out: Keyboard command (arrow) does not work
Rastan

games not working with 37B2 ROMs (so probably normal!)

1942
galaga88
Hang-on
Metalslug
out run
sly spy
super hang-on

**Comment by krabobmkd** [comment]
Thanks for testing all these, I will certainly correct a lot of those things. I didn't know some v37 could work at all, the hash code system completely differs, old roms were completely hacked when more late ones were really the original machine roms. I'm currently working on the engine to speed things up. Games with sprites issues are totally my fault and I will correct that easily.

**Comment by krabobmkd** [comment]
Just so you know, I corrected the sprites for 1943 on the last beta, but no more speed yet:
https://github.com/krabobmkd/amigamame/releases/download/beta3c/Mame106MiniMixBeta3c.lha

**Comment by stephbb75** [comment]
I will test this weekend.
I will also get the good ROMs

**Comment by stephbb75** [comment]
tested with 103 ROMs:

1941 JP : OK
1941 W : No, ROM error
1942 set 1,2,3 : OK
1943 Kai : no plane sprite
1943 : no plane sprite
1944 JP : ROM problem, does not work
1944 US : ROM problem, does not work
bad dudes : works but very very slow!
double dragon : works but slow
double dragon II : works but very slow
F1 dream : works but ckavier problem, only one key possible at a time
F1 Exhaust Note : extremely slow !!!
Galaga 88 : works but slow
Metal Slug : does not work
Metal Slug 2 : does not work
out run : works, very slow
R-TYPE : ROM not good
R-TYPR II : works a little slow
R-TYPE LEO : works a little slow
Robocop : works a little slow
Shinobi : ROM not good
Shinobi set 1 : works
Shinobi set 2 : works
Shinobi set 3 : works
Sly Spy r2 : works
Sly Spy r3 : works
Super Hang-on set 1 : ROM not good
Super Hang-on set 2 : ROM problem but works (only one key possible at a time) very slow
Super Hang-on set 3 : ROM problem but works (only one key possible at a time) very slow
Super Hang-on set 4 : ROM problem does not work
Vigilante : works

ROM Galaxia not seen in the list
P47 not seen

For the speed I did not change anything in the default settings, so the sound and no frameskip.

**Comment by krabobmkd** [comment]
Are you sure you were using "Beta3c" with the link I posted ? I totally corrected the 1943 sprite issue. Also, most of the games you mention as non working actually works with the roms I use. Be warned all neogeo (metal slugs) and irems  start with ugly screen glitch for a minute when booting: this is perfectly normal, the original machines were doing the same.

**Comment by stephbb75** [comment]
I will check this out!!!! ;-)
I may have made a mistake :-O

**Comment by stephbb75** [comment]
indeed it works better ;-)
i don't know what i did!
On the other hand the problem of the keys is very annoying to play.
On the game F1 dream it is only possible to press one key at a time (otherwise nothing happens), which is really not practical to play :-O
