### ISSUE TITLE
Beta1: Dark Palette

### ISSUE THREAD

**Issue by Jeff-Bootonic** [krabobmkd/amigamame#2]
Very promising project.
Overall, a very dark palette.

**Comment by krabobmkd** [comment]
Hello. I was taking for granted the colors was correct, yet there is indeed a "brightness" and a "gamma" color factor in internal global options. At the moment it's just hardcoded 1.0 and 0.5 , I will put that on display settings. Note color calibration is a constant issue in emulators , and there is a "incorrect color" flag for game drivers that displays wrong colors.

**Comment by krabobmkd** [comment]
corrected in beta2
