### ISSUE TITLE
Non working drivers list ( complete this list )

### ISSUE THREAD

**Issue by krabobmkd** [krabobmkd/amigamame#5]
(will be corrected for Beta2, cause was cmake badly configured for folkloric CPUs)
 Arkanoid1 ,
 double dragon 1, double dragon 2,
 all R-Types and Irem games from 1991/1994

**Comment by Jeff-Bootonic** [comment]
Every game that uses an RGB mode doesn't work. There are too many to list them all here. Just a few examples: Arkanoid Returns, Air Rescue and all NEOGEO games, which is a known issue. Maybe this information can help to mitigate the problem.

One more thing: I compiled the latest dev106, and the cheats don't work as they did in beta1. It doesn't matter if they're in the user or progdir, and even if the checkbox is ticked, it seems like the cheat.dat isn't being read. SnoopDos shows that the highscore.dat is being attempted to read, but not the cheat.dat.

Thank you for this excellent work, this will be the best version ever on a classic Amiga!

**Comment by krabobmkd** [comment]
ahah I'm working on it this morning but on another branch. Sorry for troubles. cheat.dat may be read if placed in user/

**Comment by krabobmkd** [comment]
Stop your investigation, I found the correction rgb_components must be inited in osd_create_display() for those mode. I will have RGB16PC pixel format problems to deal with.

**Comment by Jeff-Bootonic** [comment]
Oh yeah, I’m just taking a look at the old sources from AmiDog’s MAME, and all the info is in the header. Even though the version is quite old, it might help you. If you want to take a look, you can find them at http://www.amidog.se/amiga/bin/MAME_MESS_src.lha. Check video.c.

**Comment by krabobmkd** [comment]
most are corrected in beta2
